const products=[
  ['tapioca-chips','Tapioca Chips','மரவள்ளி சிப்ஸ்','200g',100,'tapioca-chips.jpg'],['palak-ribbon-pakoda','Palak Ribbon Pakoda','பாலக் ரிப்பன் பக்கோடா','200g',100,'palak-ribbon-pakoda.jpg'],['thattai','Thattai','தட்டை','200g',100,'thattai.jpg'],['carrot-chips','Carrot Chips','கேரட் சிப்ஸ்','200g',100,'carrot-chips.jpg'],['beetroot-finger-chips','Beetroot Finger Chips','பீட்ரூட் வறல் சிப்ஸ்','200g',100,'beetroot-finger-chips.jpg'],['sweet-banana-chips','Sweet Banana Chips','சுவீட் வாழை சிப்ஸ்','200g',100,'sweet-banana-chips.jpg'],['andhra-murukku','Andhra Murukku','ஆந்திரா முறுக்கு','200g',100,'andhra-murukku.jpg'],['health-mix','Health Mix','ஹெல்த் மிக்ஸ்','200g',200,'health-mix.jpg']
].map(([id,name,tamil,weight,price,image])=>({id,name,tamil,weight,price,image}));
const cart={}; const byId=id=>products.find(p=>p.id===id); const money=n=>`₹${n}`;
function quantity(p){const n=cart[p.id]||0;return n?`<div class="quantity"><button data-change="-1" data-id="${p.id}">−</button><span>${n} in cart / கூடையில்</span><button data-change="1" data-id="${p.id}">+</button></div>`:`<button data-change="1" data-id="${p.id}">Add to Cart / சேர்க்கவும்</button>`}
function render(){document.querySelector('#products').innerHTML=products.map(p=>`<article class="product"><img class="product-image" src="${p.image}" alt="${p.name}" /><div class="product-info"><div><h3>${p.name}</h3><p>${p.tamil} • ${p.weight}</p></div><span class="price">${money(p.price)}</span></div>${quantity(p)}<button class="whatsapp-product" data-whatsapp="${p.id}">◉ Order on WhatsApp / வாட்ஸ்அப்பில் ஆர்டர் செய்க</button></article>`).join('');const lines=Object.entries(cart).filter(([,n])=>n);const total=lines.reduce((sum,[id,n])=>sum+byId(id).price*n,0);document.querySelector('#cart-count').textContent=lines.length?`(${lines.reduce((s,[,n])=>s+n,0)})`:'';document.querySelector('#total').textContent=money(total);document.querySelector('#basket').innerHTML=lines.length?lines.map(([id,n])=>{const p=byId(id);return `<div class="basket-line"><div><strong>${p.name}</strong><small>${p.tamil} • ${p.weight} × ${n}</small></div><div><b class="price">${money(p.price*n)}</b><button class="remove" data-change="-1" data-id="${id}">Remove</button></div></div>`}).join(''):'<p>Your basket is empty. கூடை காலியாக உள்ளது — மேலே உள்ள பலகாரங்களைச் சேர்க்கவும்.</p>';document.querySelector('#place-order').disabled=!lines.length;document.querySelector('#whatsapp').disabled=!lines.length}
function change(id,delta){cart[id]=Math.max(0,(cart[id]||0)+delta);render()}
function messageFor(items,details=''){const total=items.reduce((s,[p,n])=>s+p.price*n,0);return `Hi Ammama, please confirm my order from Ammama's Angadi:\n\n${items.map(([p,n])=>`${p.name} (${p.tamil}) — ${p.weight} × ${n} = ${money(p.price*n)}`).join('\n')}\n\nTotal: ${money(total)}${details}`}
function whatsapp(text){window.open(`https://wa.me/919876543210?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-change]');if(b){change(b.dataset.id,Number(b.dataset.change));return}const w=e.target.closest('[data-whatsapp]');if(w){const p=byId(w.dataset.whatsapp);whatsapp(messageFor([[p,cart[p.id]||1]]))}});
document.querySelector('#whatsapp').addEventListener('click',()=>{const f=new FormData(document.querySelector('#order-form'));const details=f.get('name')?`\n\nDelivery details:\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nEmail: ${f.get('email')}\nAddress: ${f.get('address')}`:'';whatsapp(messageFor(Object.entries(cart).filter(([,n])=>n).map(([id,n])=>[byId(id),n]),details));});
document.querySelector('#order-form').addEventListener('submit',e=>{e.preventDefault();if(!Object.values(cart).some(Boolean))return;Object.keys(cart).forEach(k=>delete cart[k]);render();document.querySelector('#success').hidden=false;e.target.reset()});render();
