const products=[
  ['tapioca-chips','Tapioca Chips','மரவள்ளி சிப்ஸ்','200g',100,'tapioca-chips.jpg'],['palak-ribbon-pakoda','Palak Ribbon Pakoda','பாலக் ரிப்பன் பக்கோடா','200g',100,'palak-ribbon-pakoda.jpg'],['thattai','Thattai','தட்டை','200g',100,'thattai.jpg'],['carrot-chips','Carrot Chips','கேரட் சிப்ஸ்','200g',100,'carrot-chips.jpg'],['beetroot-finger-chips','Beetroot Finger Chips','பீட்ரூட் வறல் சிப்ஸ்','200g',100,'beetroot-finger-chips.jpg'],['sweet-banana-chips','Sweet Banana Chips','சுவீட் வாழை சிப்ஸ்','200g',100,'sweet-banana-chips.jpg'],['andhra-murukku','Andhra Murukku','ஆந்திரா முறுக்கு','200g',100,'andhra-murukku.jpg'],['health-mix','Health Mix','ஹெல்த் மிக்ஸ்','200g',200,'health-mix.jpg']
].map(([id,name,tamil,weight,price,image])=>({id,name,tamil,weight,price,image}));
const cart={}; const byId=id=>products.find(p=>p.id===id); const money=n=>`₹${n}`;
function quantity(p){const n=cart[p.id]||0;return n?`<div class="quantity"><button data-change="-1" data-id="${p.id}">−</button><span>${n} in cart / கூடையில்</span><button data-change="1" data-id="${p.id}">+</button></div>`:`<button data-change="1" data-id="${p.id}">Add to Cart / சேர்க்கவும்</button>`}
function linesInCart(){return Object.entries(cart).filter(([,n])=>n).map(([id,n])=>[byId(id),n])}
function render(){document.querySelector('#products').innerHTML=products.map(p=>`<article class="product"><img class="product-image" src="${p.image}" alt="${p.name}" /><div class="product-info"><div><h3>${p.name}</h3><p>${p.tamil} • ${p.weight}</p></div><span class="price">${money(p.price)}</span></div>${quantity(p)}<button class="whatsapp-product" data-whatsapp="${p.id}">◉ Order on WhatsApp / வாட்ஸ்அப்பில் ஆர்டர் செய்க</button></article>`).join('');const lines=linesInCart();const total=lines.reduce((sum,[p,n])=>sum+p.price*n,0);document.querySelector('#cart-count').textContent=lines.length?`(${lines.reduce((s,[,n])=>s+n,0)})`:'';document.querySelector('#total').textContent=money(total);document.querySelector('#basket').innerHTML=lines.length?lines.map(([p,n])=>`<div class="basket-line"><div><strong>${p.name}</strong><small>${p.tamil} • ${p.weight} × ${n}</small></div><div><b class="price">${money(p.price*n)}</b><button class="remove" data-change="-1" data-id="${p.id}">Remove</button></div></div>`).join(''):'<p>Your basket is empty. கூடை காலியாக உள்ளது — மேலே உள்ள பலகாரங்களைச் சேர்க்கவும்.</p>';document.querySelector('#place-order').disabled=!lines.length;document.querySelector('#whatsapp').disabled=!lines.length}
function change(id,delta){cart[id]=Math.max(0,(cart[id]||0)+delta);render()}
function messageFor(items,details=''){const total=items.reduce((s,[p,n])=>s+p.price*n,0);return `Hi Ammama, please confirm my order from Ammama's Angadi:\n\n${items.map(([p,n])=>`${p.name} (${p.tamil}) — ${p.weight} × ${n} = ${money(p.price*n)}`).join('\n')}\n\nTotal: ${money(total)}${details}`}
function whatsapp(text){window.open(`https://wa.me/918870888492?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-change]');if(b){change(b.dataset.id,Number(b.dataset.change));return}const w=e.target.closest('[data-whatsapp]');if(w){const p=byId(w.dataset.whatsapp);whatsapp(messageFor([[p,cart[p.id]||1]]))}});
document.querySelector('#whatsapp').addEventListener('click',()=>{const f=new FormData(document.querySelector('#order-form'));const details=f.get('name')?`\n\nDelivery details:\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nEmail: ${f.get('email')}\nAddress: ${f.get('address')}`:'';whatsapp(messageFor(Object.entries(cart).filter(([,n])=>n).map(([id,n])=>[byId(id),n]),details));});
function deliveryDetails(form){const data=new FormData(form);return {name:data.get('name').trim(),phone:data.get('phone').trim(),email:data.get('email').trim(),address:data.get('address').trim()}}
function setPaymentState(isPaying){const button=document.querySelector('#place-order');button.disabled=isPaying||!linesInCart().length;button.textContent=isPaying?'Opening secure payment…':'Pay Securely / பாதுகாப்பாக செலுத்துக'}
document.querySelector('#order-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const items=linesInCart();if(!items.length||!form.reportValidity())return;if(!window.Razorpay){alert('Secure checkout is unavailable. Please try again in a moment.');return}const details=deliveryDetails(form);setPaymentState(true);try{const response=await fetch('/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:items.map(([p,quantity])=>({id:p.id,quantity})),customer:details})});const order=await response.json();if(!response.ok)throw new Error(order.error||'Unable to start payment.');const checkout=new Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,name:"Ammama's Angadi",description:'Homemade traditional snacks',order_id:order.orderId,prefill:{name:details.name,contact:details.phone,email:details.email},theme:{color:'#7d3e20'},handler:async payment=>{try{const verify=await fetch('/api/verify-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payment)});const confirmed=await verify.json();if(!verify.ok||!confirmed.verified)throw new Error(confirmed.error||'Payment could not be verified.');const paidDetails=`\n\nPayment: Paid\nOrder ID: ${payment.razorpay_order_id}\nPayment ID: ${payment.razorpay_payment_id}\n\nDelivery details:\nName: ${details.name}\nPhone: ${details.phone}\nEmail: ${details.email}\nAddress: ${details.address}`;whatsapp(messageFor(items,paidDetails));Object.keys(cart).forEach(k=>delete cart[k]);render();form.reset();const success=document.querySelector('#success');success.textContent='Payment verified. Please send the WhatsApp message to confirm delivery. நன்றி!';success.hidden=false}catch(error){alert(error.message||'Payment verification failed. Please contact us before placing the order again.')}}});checkout.on('payment.failed',()=>setPaymentState(false));checkout.open()}catch(error){alert(error.message||'Unable to start payment. Please try again.');setPaymentState(false)}});render();
